(defun get-index (str)
  (interactive)
  (let ((i 0)
        (res '()))
    (mapc (lambda (s)
            (setq res (append res (list (cons i (substring-no-properties s)))))
            (setq i (+ i (+ 1 (length s)))))
          (s-split " " str))
    res))
